blogTitle = "Yvonne Zhang"
authorName = "Yvonne Zhang"
linkPrefix = "/"
# logo = "http://7xl4xb.com1.z0.glb.clouddn.com/2.png"
avatar = "http://7xl4xb.com1.z0.glb.clouddn.com/IMG_5362.JPG"
logo = "http://7xl4xb.com1.z0.glb.clouddn.com/Artboard1.png"
favicon = "http://7xl4xb.com1.z0.glb.clouddn.com/Artboard1.png"
indexImage = "http://7xl4xb.com1.z0.glb.clouddn.com/scott-webb-195100.jpg"

google_analysis_id = "UA-80503375-1"
